// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg/msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ConnType int32

const (
	ToAcceptor ConnType = 0
	ToProposer ConnType = 1
	ToLearner  ConnType = 2
)

var ConnType_name = map[int32]string{
	0: "ToAcceptor",
	1: "ToProposer",
	2: "ToLearner",
}

var ConnType_value = map[string]int32{
	"ToAcceptor": 0,
	"ToProposer": 1,
	"ToLearner":  2,
}

func (ConnType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{0}
}

//Types of messages nodes can send to one another
type Type int32

const (
	Prepare Type = 0
	Promise Type = 1
	Propose Type = 2
	Accept  Type = 3
	Commit  Type = 4
)

var Type_name = map[int32]string{
	0: "Prepare",
	1: "Promise",
	2: "Propose",
	3: "Accept",
	4: "Commit",
}

var Type_value = map[string]int32{
	"Prepare": 0,
	"Promise": 1,
	"Propose": 2,
	"Accept":  3,
	"Commit":  4,
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{1}
}

//Data type used for inter-node communication
type Msg struct {
	SlotIndex int32 `protobuf:"varint,1,opt,name=slotIndex,proto3" json:"slotIndex,omitempty"`
}

func (m *Msg) Reset()      { *m = Msg{} }
func (*Msg) ProtoMessage() {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{0}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return m.Size()
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetSlotIndex() int32 {
	if m != nil {
		return m.SlotIndex
	}
	return 0
}

//Data type for values stored in queue
type QueueRequest struct {
	Priority   int64  `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Value      string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	FromClient int32  `protobuf:"varint,3,opt,name=fromClient,proto3" json:"fromClient,omitempty"`
}

func (m *QueueRequest) Reset()      { *m = QueueRequest{} }
func (*QueueRequest) ProtoMessage() {}
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{1}
}
func (m *QueueRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueueRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueRequest.Merge(m, src)
}
func (m *QueueRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueueRequest proto.InternalMessageInfo

func (m *QueueRequest) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *QueueRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *QueueRequest) GetFromClient() int32 {
	if m != nil {
		return m.FromClient
	}
	return 0
}

//Type used for sending information about a slot's value
type SlotValue struct {
	Type      Type   `protobuf:"varint,1,opt,name=type,proto3,enum=msg.Type" json:"type,omitempty"`
	SlotIndex int32  `protobuf:"varint,2,opt,name=slotIndex,proto3" json:"slotIndex,omitempty"`
	Value     string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *SlotValue) Reset()      { *m = SlotValue{} }
func (*SlotValue) ProtoMessage() {}
func (*SlotValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0f0a1b324c95b77, []int{2}
}
func (m *SlotValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SlotValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SlotValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SlotValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlotValue.Merge(m, src)
}
func (m *SlotValue) XXX_Size() int {
	return m.Size()
}
func (m *SlotValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SlotValue.DiscardUnknown(m)
}

var xxx_messageInfo_SlotValue proto.InternalMessageInfo

func (m *SlotValue) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Prepare
}

func (m *SlotValue) GetSlotIndex() int32 {
	if m != nil {
		return m.SlotIndex
	}
	return 0
}

func (m *SlotValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("msg.ConnType", ConnType_name, ConnType_value)
	proto.RegisterEnum("msg.Type", Type_name, Type_value)
	proto.RegisterType((*Msg)(nil), "msg.Msg")
	proto.RegisterType((*QueueRequest)(nil), "msg.QueueRequest")
	proto.RegisterType((*SlotValue)(nil), "msg.SlotValue")
}

func init() { proto.RegisterFile("msg/msg.proto", fileDescriptor_d0f0a1b324c95b77) }

var fileDescriptor_d0f0a1b324c95b77 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x31, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0xef, 0x92, 0xb6, 0x36, 0x4f, 0x5b, 0x8e, 0xc3, 0xa1, 0x88, 0x1e, 0xa5, 0x2e, 0xa5,
	0x43, 0x05, 0x9d, 0xc4, 0x49, 0x8b, 0x83, 0xa0, 0x50, 0x63, 0x71, 0x70, 0x10, 0x6b, 0x7d, 0x86,
	0x40, 0x92, 0x8b, 0x77, 0x17, 0xb1, 0x9b, 0x1f, 0xc1, 0x8f, 0xe1, 0x47, 0x71, 0xec, 0xd8, 0xd1,
	0xa6, 0x8b, 0x63, 0x3f, 0x82, 0x24, 0x11, 0x5b, 0xdd, 0xde, 0xef, 0xcf, 0x7b, 0xff, 0xff, 0x1f,
	0x1e, 0xd4, 0x42, 0xed, 0xed, 0x85, 0xda, 0xeb, 0xc6, 0x4a, 0x1a, 0xc9, 0xed, 0x50, 0x7b, 0xad,
	0x5d, 0xb0, 0x2f, 0xb4, 0xc7, 0xb7, 0xc1, 0xd1, 0x81, 0x34, 0x67, 0xd1, 0x03, 0xbe, 0x34, 0x68,
	0x93, 0xb6, 0xcb, 0xee, 0x52, 0x68, 0xdd, 0xc1, 0xc6, 0x65, 0x82, 0x09, 0xba, 0xf8, 0x94, 0xa0,
	0x36, 0x7c, 0x0b, 0xaa, 0xb1, 0xf2, 0xa5, 0xf2, 0xcd, 0x38, 0x5f, 0xb6, 0xdd, 0x5f, 0xe6, 0x9b,
	0x50, 0x7e, 0x1e, 0x06, 0x09, 0x36, 0xac, 0x26, 0x6d, 0x3b, 0x6e, 0x01, 0x5c, 0x00, 0x3c, 0x2a,
	0x19, 0xf6, 0x02, 0x1f, 0x23, 0xd3, 0xb0, 0xf3, 0x80, 0x15, 0xa5, 0x75, 0x0b, 0xce, 0x55, 0x20,
	0xcd, 0x75, 0xbe, 0xbc, 0x03, 0x25, 0x33, 0x8e, 0x31, 0xb7, 0xae, 0xef, 0x3b, 0xdd, 0xac, 0xf2,
	0x60, 0x1c, 0xa3, 0x9b, 0xcb, 0x7f, 0xbb, 0x5a, 0xff, 0xba, 0x2e, 0xf3, 0xed, 0x95, 0xfc, 0xce,
	0x21, 0x54, 0x7b, 0x32, 0x8a, 0x32, 0x17, 0x5e, 0x07, 0x18, 0xc8, 0xe3, 0xd1, 0x08, 0x63, 0x23,
	0x15, 0x23, 0x05, 0xf7, 0x95, 0x8c, 0xa5, 0x46, 0xc5, 0x28, 0xaf, 0x81, 0x33, 0x90, 0xe7, 0x38,
	0x54, 0x11, 0x2a, 0x66, 0x75, 0x4e, 0xa1, 0x94, 0x9f, 0xad, 0xc3, 0x5a, 0x5f, 0x61, 0x3c, 0x54,
	0xc8, 0x48, 0x01, 0x32, 0xf4, 0x35, 0x32, 0xfa, 0x03, 0xd9, 0x39, 0xb3, 0x38, 0x40, 0xa5, 0xf0,
	0x66, 0x76, 0x36, 0xf7, 0x64, 0x18, 0xfa, 0x86, 0x95, 0x4e, 0x8e, 0x26, 0x33, 0x41, 0xa6, 0x33,
	0x41, 0x16, 0x33, 0x41, 0x5f, 0x53, 0x41, 0xdf, 0x53, 0x41, 0x3f, 0x52, 0x41, 0x27, 0xa9, 0xa0,
	0x9f, 0xa9, 0xa0, 0x5f, 0xa9, 0x20, 0x8b, 0x54, 0xd0, 0xb7, 0xb9, 0x20, 0x93, 0xb9, 0x20, 0xd3,
	0xb9, 0x20, 0x37, 0xe5, 0x6e, 0xf6, 0xb0, 0xfb, 0x4a, 0xfe, 0xb1, 0x83, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x48, 0x52, 0x05, 0xd4, 0xc2, 0x01, 0x00, 0x00,
}

func (x ConnType) String() string {
	s, ok := ConnType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x Type) String() string {
	s, ok := Type_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Msg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Msg)
	if !ok {
		that2, ok := that.(Msg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SlotIndex != that1.SlotIndex {
		return false
	}
	return true
}
func (this *QueueRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*QueueRequest)
	if !ok {
		that2, ok := that.(QueueRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Priority != that1.Priority {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	if this.FromClient != that1.FromClient {
		return false
	}
	return true
}
func (this *SlotValue) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SlotValue)
	if !ok {
		that2, ok := that.(SlotValue)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.SlotIndex != that1.SlotIndex {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	return true
}
func (this *Msg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&msg.Msg{")
	s = append(s, "SlotIndex: "+fmt.Sprintf("%#v", this.SlotIndex)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *QueueRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&msg.QueueRequest{")
	s = append(s, "Priority: "+fmt.Sprintf("%#v", this.Priority)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "FromClient: "+fmt.Sprintf("%#v", this.FromClient)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SlotValue) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&msg.SlotValue{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "SlotIndex: "+fmt.Sprintf("%#v", this.SlotIndex)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMsg(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Msg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Msg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Msg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SlotIndex != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.SlotIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueueRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueueRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueueRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FromClient != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.FromClient))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if m.Priority != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.Priority))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SlotValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SlotValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SlotValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SlotIndex != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.SlotIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.Type != 0 {
		i = encodeVarintMsg(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsg(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsg(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Msg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotIndex != 0 {
		n += 1 + sovMsg(uint64(m.SlotIndex))
	}
	return n
}

func (m *QueueRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Priority != 0 {
		n += 1 + sovMsg(uint64(m.Priority))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.FromClient != 0 {
		n += 1 + sovMsg(uint64(m.FromClient))
	}
	return n
}

func (m *SlotValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovMsg(uint64(m.Type))
	}
	if m.SlotIndex != 0 {
		n += 1 + sovMsg(uint64(m.SlotIndex))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func sovMsg(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsg(x uint64) (n int) {
	return sovMsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Msg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Msg{`,
		`SlotIndex:` + fmt.Sprintf("%v", this.SlotIndex) + `,`,
		`}`,
	}, "")
	return s
}
func (this *QueueRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&QueueRequest{`,
		`Priority:` + fmt.Sprintf("%v", this.Priority) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`FromClient:` + fmt.Sprintf("%v", this.FromClient) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SlotValue) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SlotValue{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`SlotIndex:` + fmt.Sprintf("%v", this.SlotIndex) + `,`,
		`Value:` + fmt.Sprintf("%v", this.Value) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMsg(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Msg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Msg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Msg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotIndex", wireType)
			}
			m.SlotIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotIndex |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueueRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueueRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueueRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priority", wireType)
			}
			m.Priority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Priority |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromClient", wireType)
			}
			m.FromClient = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FromClient |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SlotValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SlotValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SlotValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotIndex", wireType)
			}
			m.SlotIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotIndex |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsg
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsg
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsg
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsg
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsg        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsg          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsg = fmt.Errorf("proto: unexpected end of group")
)
