proposers:
  count: 2
  values:
    - "cat" # proposer 1 uses value "cat"
    - "dog" # proposer 2 uses value "dog"
acceptors:
  count: 3
  initIP: "127.0.0.1" # start with this ip
  incrementIP: false # whether each node has a unique ip
  initPort: "8000"
  incrementPort: true # whether each node has a unique port
