msgSize: 0 # size of message in bytes
bufferSize: 4096000
acceptors:
  count: 3
  ip:
    - "10.128.15.213"
    - "10.128.15.214"
    - "10.128.15.215"
  port:
    - "5005"
    - "5005"
    - "5005"
proposers:
  count: 1
  ip:
    - "10.128.15.216"
  port:
    - "5005"