msgSize: 0 # size of message in KBs
quorum: 2
acceptors:
  count: 3
  ip:
    - "127.0.0.1"
    - "127.0.0.2"
    - "127.0.0.3"
  port:
    - "8000
    - "8001"
    - "8002"
proposers:
  count: 1
  ip:
    - "127.0.0.1"
  port:
    - "9000"