proposers:
  count: 2
  values:
    - "cat" # proposer 1 uses value "cat"
    - "dog" # proposer 2 uses value "dog"
acceptors:
  count: 3
  ipRange: "localhost" # uses ip address in this range
  portRange: "8000-8010" # acceptor 1 uses :8000, acceptor 2 uses :8001, etc.