timeout: 10 # time out in seconds for client
acceptors:
  count: 3
  initIP: "127.0.0.1" # start with this ip
  incrementIP: false # whether each node has a unique ip
  initPort: "8000"
  incrementPort: true # whether each node has a unique port
proposers:
  count: 1
  initIP: "127.0.0.1" # start with this ip
  incrementIP: false # whether each node has a unique ip
  initPort: "9000"
  incrementPort: true # whether each node has a unique port
